version: '3.5'

services:
  # Producer
  destroyer:
    image: destroyer:latest
    container_name: destroyer
    restart: on-failure
    build:
      context: .
      dockerfile: src/destroyer-service/Dockerfile
    depends_on:
      - database
      - broker
    ports:
      - '5051:5051'
    environment:
      - PORT=5051
      - PULSAR_URL=pulsar://broker:6650
      - SERVICE_NAME=destroyer
      - TOPIC_NAME=targets.acquired
      - DB_URL=mongodb://database:27017
      - DB_NAME=targets

  # Consumer
  deathstar:
    image: deathstar:latest
    container_name: deathstar
    restart: on-failure
    build:
      context: .
      dockerfile: src/deathstar-service/Dockerfile
    depends_on:
      - database
    environment:
      - PULSAR_URL=pulsar://broker:6650
      - SERVICE_NAME=deathstar
      - TOPIC_NAME=targets.acquired
      - DB_URL=mongodb://database:27017
      - DB_NAME=targets

  # API Gateway
  api-gateway:
    image: api-gateway:latest
    container_name: api
    restart: on-failure
    build:
      context: .
      dockerfile: src/api-gateway/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - DESTROYER_URL=destroyer:5051

  # Event broker
  broker:
    image: apachepulsar/pulsar:2.4.0
    container_name: broker
    ports:
      - '6650:6650'
      - '8080:8080'
    volumes:
      - $PWD/data/pulsar:/pulsar/data
    command:
      bin/pulsar standalone


  # Database
  database:
    image: mongo
    container_name: mongo
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - $PWD/data/db:/data/db
